* Week 2
** What is a Company Worth?
*** Key Terms
**** Instrinsic Value
1. The actual value of a company or an asset based on an underlying
perception of its true value including all aspects of the business, in
terms of both tangible and intangible factors. This value may or may
not be the same as the current market value. Value investors use a
variety of analytical techniques in order to estimate the intrinsic
value of securities in hopes of finding investments where the true
value of the investment exceeds its current market value.  

2. For call options, this is the difference between the underlying stock's price
and the strike price. For put options, it is the difference between
the strike price and the underlying stock's price. In the case of both
puts and calls, if the respective difference value is negative, the
intrinsic value is given as zero.

http://www.investopedia.com/terms/i/intrinsicvalue.asp

**** Capital Assets Pricing Model
- https://en.wikipedia.org/wiki/Capital_asset_pricing_model

A model that describes the relationship between risk and expected
return and that is used in the pricing of risky securities. Capital
Asset Pricing Model (CAPM)The general idea behind CAPM is that
investors need to be compensated in two ways: time value of money and
risk.

The time value of money is represented by the risk-free (rf) rate in
the formula and compensates the investors for placing money in any
investment over a period of time. The other half of the formula
represents risk and calculates the amount of compensation the investor
needs for taking on additional risk.

This is calculated by taking a risk measure (beta) that compares the
returns of the asset to the market over a period of time and to the
market premium (Rm-rf).

Read more: http://www.investopedia.com/terms/c/capm.asp

*** Support Resources
**** Pandas Tutorial
- http://pandas.pydata.org/pandas-docs/stable/dsintro.html

**** Numpy Tutorial
- http://www.python-course.eu/numpy.php

*** Intrinsic value: Value of future dividends
- multiple methods of estimating a company's value
  - market cap
    - what the stock market thinks it's work
    - num shares * current stock price
  - future dividends
  - book value

**** Notial Company
- print $1/year each year, forever
- 

- What is the current value of a future $1
- I promise to pay you $1 in a year
- How much will you give me to get that $1 back

- .95
- This means you value value a dollar a year from now, to be worth 95 cents today.
- This means the future value of that dollar is 0.95
- This is also called a discount rate


- One year, .95
- Second year, .95 ^ 2 => .9025
- Third year, .95 ^ 3 => .857375
- ...
- 0.00


- Present Value
- SUM( future dollars )
- .95 ^ i

- "future income generated by the asset, and discouting it to the present value"
- sum(dividend * gamma ^ i)
- dividend * 1 / (1 - gamma)

 
- 1.00 / (1 - .95) => 1 / .05 => $20.00


**** How does information affect price
- Local effect all local
- Global can effect all companies

*** Fundamental Analysis of Company Value

**** What's a Company Worth?
Fundamental analytis: Value is sum of 
- Book value
  - value of the parts
- Future returns, or "intrinsic" value
  - "future income generated by the asset, and discouting it to the present value"
  - sum(dividend * gamma ^ i)
  - dividend * 1 / (1-gamma)


Book Value
"total assets minus intagible assets and liabilities"

Why not ask the market?
How does the market know?

value = #shares outstanding * price
which is the Market Capitalization

S&P 500

- the market is an efficient processor of information
- The Efficient Markets Hypothesis

- What is the market cap of a company with 100000 outstanding shares which are priced at 576.46
- 57,646,000

** Capital Assets Pricing Model
*** Capital Assets Pricing Model
CAPM
- Assumptions
- Implications
- How can it be used in fund management

Reading: Grinold & Kahn, Chapter 2

Capital Assets Pricing Model
Introduced by Jack Treynor, William Sharpe, John Lintner and Jan Mossin (1966)
Sharpe, Markowitz and Merton Miller jointly received the Nobel Prize

Lead to Index investing and the Efficient Markets Hypothesis

- Return on stock has two components
  - Systematic (the market)
  - Residual

- Expected value of residual = 0
- Market return
  - Risk free rate of return +
  - Excess return

- return = systematic + residual
-  ri = Bi rm + ai

- Expected value of the residual is 0 per CAPM
- Residual === Execess return = 0 for CAPM

**** The Market Portfolio

|-------+---------+------------------------+-----------------------|
| US    | S&P 500 | Weighted by market cap | 500 largest companies |
|       | DJ 30   | Picked by WSJ          |                       |
| UK    | FTA     |                        |                       |
| Japan | TOPIX   |                        |                       |
|-------+---------+------------------------+-----------------------|

*** CAPM: What is Beta?

daily return = ( today's price / yesterday's price ) - 1

ri = Beta rm + residual (alpha i)

rm = return of the market

residual -- information that can be exploit?
capm has an expectation that residual is 0 and you can't forcast it

Per Capm beta is what is important

ri(t) = betai * rm (t) + alphai


Use linear regression (line fitting) to find beta and alpha

The slope of the line is Beta
Beta times the amount that the market moves gives you where the return of your stock ends up

Alpha is the point where it intercepts the y axis


**** Beta and Correlation are Different

- Beta is the slope of the line

- Correlation coefficient
How close the points are to the line
1.0 means perfect correlation
-1.0 means perfect anti-correlation




**** CAPM: Expeced Residual = 0
- believe that residual is 0 or random

Active Portfolio MAnagement View
- residual is alpha and you can forcast and take advantage


**** How Hedge Funds Use CAPM
- CAPM: Implications
- Expected excess returns are proportional to beta
 - Beta needs to > 1.0 (do better than the market)
 - > Beta => implie greater risk

- Beta of a portfolio = weighted sum of betas of components

***** Portfolio Beta Examples
Return on a portfolio = Sum on the return on the individual components

Weight on how much of each you have in your portfolio

Beta of the whole portfolio
Sum of the weights * Beta of each stock



- $1000 of XOM with a beta of 1.0
- $1000 of IBM with a beta of 2.0

- The weight of each is .5

- Bp = .5*1.0 + .5*2 = 1.5


****** Quiz

- 1000 of IBM
- 2000 of Google
- 1000 of XOM

What is the weight of IBM

.5 = goog
.25 = ibm
.25 = xom


1000 / (1000 + 2000 + 1000)

***** CAPM Market Risk : Example

What if you think IBM will go up but the market goes down and drags it with it
IBM will still be above the market 
That difference is Alpha

SPY = index of SP500


1 = IBM                        Beta - 1.0
2 = SPY  -> ETF of SP500       Beta - 1.0 (by definition)

Weighting

w1 = .50 IBM
w2 = .50 SPY (short so negative)


r1 = w1 * b1 + alpha
   = .5 * 1.0  + (positive, we think IBM will go up)

r2 = -.5 * 1.0 + random/0


r1 = .5 + (.5 * alpha)
r2 = -.5 + 0
---------------
rt  = .5 alpha

Positive expectation

Removing market risk






*** Summary


Understand assumptions of the CAPM
Understand implications of the CAPM
   Build portofolios to remove risk
Read chapter 2 of Grinold and Kahn

** Installing QSTK Sotware

- http://sourabhbajaj.com/mac-setup/Python/numpy.html
- https://github.com/Homebrew/homebrew-science
- http://quantlabs.net/blog/2015/12/instruction-to-get-python-data-science-working-on-mac/

- https://github.com/weiyialanchen/algotrading
- https://github.com/weiyialanchen/MacInstallation

- http://wiki.quantsoftware.org/index.php?title=QSToolKit_Installation_Guide_Mac


*** Install script
- http://sourabhbajaj.com/mac-setup/Python/numpy.html
- https://github.com/weiyialanchen/algotrading

$ brew tap samueljohn/python
$ brew tap homebrew/science
$ brew install gcc

# System installs
$ pip install virtualenv
$ pip install nose
$ pip install pyparsing
$ pip install python-dateutil
$ pip install pep8


# Install into env
$ virtualenv env
$ source env/bin/activiate
l$ pip install numpy
$ pip install scipy
$ pip install matplotlib

$ pip install pandas
$ pip install scikits.statsmodels
$ pip install scikit-learn

# https://pypi.python.org/pypi/QSTK/0.2.8
# https://github.com/QuantSoftware/QuantSoftwareToolkit
$ pip install QSTK

*** Examples

cd ~/QSTK
curl -O https://raw.githubusercontent.com/weiyialanchen/MacInstallation/master/Examples.zip
unzip Examples.zip

*** Validation

- http://stackoverflow.com/a/21789908
- Create a file
- $HOME/.matplotlib/matplotlibrc
- with contents
- backend: TkAgg

**** Results

(env) blucas.local:~/tmp/testing/Examples$ python Validation.py
python Validation.py
Python Details : 
2.7.10 (default, Sep 23 2015, 04:34:21) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.72)]
Your Python Version is :  2.7.10
QSTK uses Python 2.7.X (2.7.3 recommended and supported)
Please make sure you're using the correct python version.

Current Directory :  /Users/brad/tmp/testing/Examples

Files in the current directory
Basic
DataAccess
EventProfiler
Features
FeatureSearch
KNN
Validation.py

Numpy is installed and the version used is :  1.12.0
Please make sure you're using version >= 1.6.1

Matplotlib is installed and version is :  2.0.0
Please make sure you're using version >= 1.1.0

Pandas is installed and the version used is :  0.19.2
Please make sure you're using version >= 0.7.3

Scipy is installed and the version used is :  0.18.1
Please make sure you're using version >= 0.9.0

Dateutil is installed and the version used is :  1.5
Please make sure you're using version == 1.5

Setuptools is installed and the version used is :  34.2.0
Please make sure you're using version >= 0.6

datetime is installed and can be imported

All dependencies are installed and working

QSTK is installed and can be imported

/Users/brad/tmp/testing/env/lib/python2.7/site-packages/QSTK/qstkutil/qsdateutil.py:36: FutureWarning: TimeSeries is deprecated. Please use Series
  return pd.TimeSeries(index=dates, data=dates)
QSTK.qstkutil is installed and can be imported

QSTK.qstkstudy is installed and can be imported

Scratch Directory:  /var/folders/rk/mf8fv5js2cq5rdtny2qd_tt00000gn/T/QSScratch
Data Directory:  /Users/brad/tmp/testing/env/lib/python2.7/site-packages/QSTK/qstkutil/../QSData
                      MSFT    GOOG
2012-02-10 16:00:00  29.90  605.91
2012-02-13 16:00:00  29.98  612.20
2012-02-14 16:00:00  29.86  609.76
2012-02-15 16:00:00  29.66  605.56
2012-02-16 16:00:00  30.88  606.52
2012-02-17 16:00:00  30.84  604.64
2012-02-21 16:00:00  31.03  614.00
2012-02-22 16:00:00  30.86  607.94
2012-02-23 16:00:00  30.96  606.11


Correct Output using the Default Data should be : 
Assignments use this data for grading
                      MSFT    GOOG
2012-02-10 16:00:00  29.90  605.91
2012-02-13 16:00:00  29.98  612.20
2012-02-14 16:00:00  29.86  609.76
2012-02-15 16:00:00  29.66  605.56
2012-02-16 16:00:00  30.88  606.52
2012-02-17 16:00:00  30.84  604.64
2012-02-21 16:00:00  31.03  614.00
2012-02-22 16:00:00  30.86  607.94
2012-02-23 16:00:00  30.96  606.11

Close price of MSFT on 2012/2/15 is :  29.66
Data looks correct as the close price in default data is 29.66

Everything works fine: You're all set.
(env) blucas.local:~/tmp/testing/Examples$ 

** Homework 0: Install QSTK
